spring:
  jpa:
    show-sql: true
  multi-datasource:
    product:
      url: "jdbc:mysql://210.179.122.169:3306/product?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8"
      username: "ezpmp"
      password: dlwmvldpavl
      driverClassName: com.mysql.cj.jdbc.Driver

    program:
      url: "jdbc:mysql://210.179.122.169:3306/program?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8"
      username: "ezpmp"
      password: dlwmvldpavl
      driverClassName: com.mysql.cj.jdbc.Driver

  mail:
    smtp:
      host: smtp.gmail.com
      port: 587
      user: email
      pass: password
      sender: ezpmp
servlet:
    multipart:
      location: D:/image
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 80

ezpmp:
  swagger:
    base-package: "com.ezpmp.api"
    enabled: false
  redis: ### Redis 설정
    holdingTime: '1'
    enabled: true
    host: localhost
    port: 6379
    password: ""
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2

properties:
  aesKey: dlwmvldpavl!!234