apiVersion: v1
kind: Namespace
metadata:
  name: ezpmp-product-api
---
apiVersion: v1
kind: Service

metadata:
  name: product-api-svc
  namespace: ezpmp-product-api
spec:
  selector:
    app: product-api

  ports:
    - protocol: TCP
      port: 1070
      targetPort: http
    # nodePort: 30001
  #type: NodePort



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: ezpmp-product-api
  labels:
    app: product-api


spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api

    spec:
      containers:
        - name: product-api
          image: ezpmp/product-api
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 1070
          volumeMounts:
            - name: log-volume
              mountPath: /logs

        - name: fluent-bit
          image: fluent/fluent-bit
          volumeMounts:
            - name: log-volume
              mountPath: /logs
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: config
              mountPath: /fluent-bit/etc/parsers_springboot.conf
              subPath: parsers_springboot.conf

      volumes:
        - name: log-volume
          emptyDir: { }
        - name: config
          configMap:
            name: fluent-bit-config
