spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://218.39.10.59:3306/program?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true
    username: ezpmp
    password: dlwmvldpavl    
  mail:
    smtp:
      host: smtp.gmail.com
      port: 587
      user: email
      pass: password
      sender: ezpmp
servlet:
    multipart:
      location: D:/image
      max-file-size: 30MB
      max-request-size: 30MB

mybatis:
  mapper-locations: mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 1030

ezpmp:
  swagger:
    base-package: "com.sample.api"
    enabled: false
  redis: ### Redis 설정
    holdingTime: '1'
    enabled: true
    host: localhost
    port: 6379
    password: ""
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
application:
  serverUrl:
    commonApiUrl: http://localhost:1000